---
- hosts: ubuntu
  remote_user: ubuntu
  tasks:
  - name: Creating a file with content
    copy:
      dest: "~/text.sh"
      mode: 0755
      content: |
        apt get update
        apt intall nginx
  - name: Create multiple files
    file: 
      path: "{{ item }}"
      state: touch
    with_items:
    - test01.txt
    - test02.txt
    - test03.txt
    - test04.txt
  - name: Creating a new directory
    file:
      path: "~/text"
      state: directory