---
- name: Manage users and groups
  hosts: amazon-linux
  remote_user: ec2-user
  become: yes
  gather_facts: false
  vars:
    ansible_cfg:
      defaults:
        host_key_checking: false
  tasks:
    - name: Ensure group 'devs' exists
      ansible.builtin.group:
        name: devs
        state: present

    - name: Ensure user 'don' exists and is in 'devs' group
      ansible.builtin.user:
        name: don
        groups: devs
        append: yes
        state: present

    - name: Ensure user 'jake' exists, is in 'devs' group, and has a specific shell
      ansible.builtin.user:
        name: jake
        groups: devs
        append: yes
        shell: /bin/bash
        state: present
    - name: create a file
      file: 
        path: /tmp/test
        state: directory

- name: Install and configure Nginx web server on Ubuntu
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled on boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Confirm Nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Check if Nginx is running
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_status

    - name: Print Nginx status
      ansible.builtin.debug:
        msg: "Nginx is {{ nginx_status.stdout }}"

