---
- name: Create Users & Groups
  hosts: all
  remote_user: ec2-user
  become: yes
  # gather_facts: false
  # vars:
  #   ansible_cfg:
  #     defaults:
  #       host_key_checking: false
  tasks:
    - name: Create group
      group:
        name: dev
        state:  present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        group: dev
      loop:
        - jake
        - tom
        - jana
        - algreim

    - name: Remove the user algerim
      ansible.builtin.user:
        name: algreim
        state: absent
        remove: yes
     
# - name: Create Users & Groups
#   hosts: amazon-linux
#   remote_user: ec2-user
#   become: yes
#   tasks:
#     - name: Create group
#       group:
#         name: dev
#         state:  present

#     - name: Create Users Task
#       user:
#         name: "{{ item }}"
#         state: present
#         shell: /bin/bash
#         group: dev
#       loop:
#         - jake
#         - tom
#         - algreim