---
- name: Create Users & Groups
  hosts: ubuntu:ec2-user
  remote_user: ubuntu:ec2-user
  become_user: yes
  tasks:
    - name: Create group
      group:
        name: dev
        state: present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        group: dev
      loop:
        - jake
        - tom
        - algreim